#!/usr/bin/env bash

set -euo pipefail

command=${1:-}
args=${@:2}

SOURCE="${BASH_SOURCE[0]}"
while [ -h "$SOURCE" ]; do
	HARPOON_ROOT="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
	SOURCE="$( readlink "$SOURCE" )"
	[[ ${SOURCE} != /* ]] && SOURCE="$HARPOON_ROOT/$SOURCE"
done
export HARPOON_ROOT="$( cd -P "$( dirname "$SOURCE" )" && pwd )"

export TASKS_ROOT=${HARPOON_ROOT}/tasks
export SERVICES_ROOT=${HARPOON_ROOT}/services
export VENDOR_ROOT=${HARPOON_ROOT}/vendor
export IMAGES_ROOT=${HARPOON_ROOT}/images


if [[ "$command" == "initpath" ]]; then
	echo "${HARPOON_ROOT}/completion/init.sh" && exit 0
fi


# functions
for f in $(ls ${HARPOON_ROOT}/core/func); do
	source ${HARPOON_ROOT}/core/func/${f}
done


# variables
for f in $(ls ${HARPOON_ROOT}/core/vars); do
	source ${HARPOON_ROOT}/core/vars/${f}
done

source ${HARPOON_ROOT}/core/parse_cmd.sh

TASK_NAME=$(parse_cmd ${command})

if [[ -v USE_DIND && "$TASK_NAME" != "dind" ]]; then
	print_info "Harpoon is running in dind mode"
	${DIND_EXEC_TTY} harpoon "$@"
	exit $?
fi

# this should always be loaded AFTER core vars and func
source ${HARPOON_ROOT}/core/boot.sh

source ${TASKS_ROOT}/tasks.sh

source ${SERVICES_ROOT}/services.sh

# setup temp directory
mkdir -p ${HARPOON_TEMP}

case "${command:-}" in
	compose) ## <arg>... %% 🐳  Run docker-compose for the Harpoon core services
		${HARPOON_DOCKER_COMPOSE} ${args} ;;

	cmplt)
		source ${HARPOON_ROOT}/completion/completion.sh ;;

	config-dnsmasq)
		config_dnsmasq ;;

	config-docker)
		config_docker ;;

	config-docker-network)
		config_docker_network ;;

	env) ## %% Show environment variables
		if [ -v PAGER ]; then
			env | sort | ${PAGER}
		else
			env | sort
		fi
		;;

	help) ## [<task> | <service>] %% ⁉️  Get help
		if [[ "$args" == "" ]]; then all_help; fi

		# try tasks
		task_exists ${args}

		if [ -v TASK_ROOT ]; then
			task_help
		else
			# try services
			service_exists ${args}

			if [ -v SERVICE_ROOT ]; then
				service_help ${args};
			elif [ -v ROOT_TASKS_FILE ]; then
				# try custom task handler in working directory
				tasks_help
			fi
		fi
		;;

	show-docker-host-ip)
		echo ${HARPOON_DOCKER_HOST_IP} ;;

	up) ## %% 🏁  Install Harpoon and start core services
		up ;;

	install) ## %% Alias for `up`
		up ;;

	down) ## [<all>] %% 🔽  Stop and remove Harpoon core, and optionally, supporting services
		down ${args} ;;

	uninstall) ## %% Alias for `down`
		down ${args} ;;

	reset) ## %% 🌯  Stop, remove, and restart Harpoon core services
		reset ;;

	self-update) ## %% 💫  Update Harpoon and plugins
		self_update ;;

	selfupdate) ## %% Alias for `self-update`
		self_update ;;

	clean) ## [<all>] %% 🛀  Completely uninstall Harpoon core, and optionally, all supporting services
		clean ${args} ;;

	status) ## %% 🚥  Display the status of Harpoon core services
		DOWN_HOSTS=0
		for i in dnsmasq consul traefik; do
			IS_UP=$(${HARPOON_DOCKER_COMPOSE} ps ${i} | grep 'Up') || true
			if [[ ${IS_UP} ]]; then
				printf "%-20s%s\n" "${i}" "${UP}"
			else
				printf "%-20s%s\n" "${i}" "${DOWN}"
				DOWN_HOSTS+=1
			fi
		done
		if [ ${DOWN_HOSTS} -gt 0 ]; then
			exit 1
		fi
		;;

	tasks:list) ## %% 👓  List tasks available in Harpoon
		tasks ;;

	services:list) ## %% 👓  List services available in Harpoon
		services ;;

	services:status) ## %% 🚦  Display the status for all supporting services
		services_status ;;

	stfu) ## %% 🤐  Please stop talking
		echo "export HARPOON_SPEECH=false" >> $HOME/harpoon.env.sh ;;

	greet)
		speak_greeting ;;

	radio)
		say -v Fred -r 190 "Fitter. Happier. More productive." ;;

	*)
		if [ "${TASK_NAME}" == "" ]; then all_help; fi

		# try tasks
		task_exists ${TASK_NAME}

		if [ -v TASK_ROOT ]; then
			source ${TASK_ROOT}/handler.sh
		else
			# try services
			service_exists ${TASK_NAME}

			if [ -v SERVICE_ROOT ]; then
				handle_service ${TASK_NAME} ${command};
			elif [ -v ROOT_TASKS_FILE ]; then
				# try custom task/command handler in working directory
				command=${command#${PROJECT_TASK_PREFIX}:}
				source ${ROOT_TASKS_FILE}
			fi
		fi
esac
