#!/usr/bin/env bash

set -euo pipefail

command=${1:-}
args=${@:2}

export SOURCE="${BASH_SOURCE[0]}"
while [ -h "$SOURCE" ]; do # resolve $SOURCE until the file is no longer a symlink
  HARPOON_ROOT="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
  SOURCE="$(readlink "$SOURCE")"
  [[ ${SOURCE} != /* ]] && SOURCE="$HARPOON_ROOT/$SOURCE" # if $SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
done

# roots
export HARPOON_ROOT="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
export SERVICES_ROOT=${HARPOON_ROOT}/services

export ROOT_TASKS_FILE="${HARPOON_ROOT}/harpoon"

# variables
source ${HARPOON_ROOT}/core/vars/env.sh
source ${HARPOON_ROOT}/core/vars/docker.sh
source ${HARPOON_ROOT}/core/vars/traefik.sh

print_help() {
	help=$(grep -E '^\t[a-zA-Z:|_-]+\)\s##\s.*$' ${1} | sort | awk 'BEGIN {FS = "\\).*?## |%%"}; {c=$1" "$2; printf "\033[36m%-34s\033[0m %s\n", c, $3}')
	echo -e "$help"
}

source ${HARPOON_ROOT}/services/services.sh

traefik_storeconfig() {
	if [ ! -f core/traefik/acme/acme.json ]; then
		echo "{ }" > core/traefik/acme/acme.json
	fi
	chmod 600 core/traefik/acme/acme.json
	${HARPOON_DOCKER_COMPOSE} run --rm traefik storeconfig
}

export HTTPIE="docker run --rm -i -v ${PWD}:${PWD} -w ${PWD} --net=harpoon -e 'TERM=xterm' alpine/httpie"

case "${command:-}" in
	docker) ## <arg>...	%% 🐳  Run docker in the Harpoon environment
		docker ${args} ;;

	docker-compose|dc) ## <arg>... %% 🐳  Run docker-compose in the Harpoon environment
		${HARPOON_DOCKER_COMPOSE} ${args} ;;

	env) ## %% Show environment variables
		env | ${PAGER} ;;

	http) ## <arg...> %% 🌎  HTTPie
		${HTTPIE} ${args} ;;

	show-nameserver-ip)
		echo ${NAMESERVER_IP} ;;

	install) ## %% ▶️  Install Harpoon
		docker network create ${HARPOON_DOCKER_NETWORK} --subnet 10.254.253.0/24 || true
		${HARPOON_DOCKER_COMPOSE} pull
		${HARPOON_DOCKER_COMPOSE} up -d cadvisor dnsmasq consul
#		sleep 10
#		traefik_storeconfig
		${HARPOON_DOCKER_COMPOSE} up -d traefik

		sudo mkdir -p /etc/resolver

		# Add fixed loopback alias for container connectivity to services running locally (when running Docker for Mac)
		uname | grep Darwin && sudo ifconfig lo0 alias 10.254.252.1/32 || true

		#sudo ifconfig lo:0 10.254.253.1/32

		if [ ${CUSTOM_DOMAIN:-} ]; then
			echo "nameserver ${NAMESERVER_IP}" | sudo tee /etc/resolver/${CUSTOM_DOMAIN}
		fi

		echo "nameserver ${NAMESERVER_IP}" | sudo tee /etc/resolver/harpoon.dev
		echo "nameserver ${NAMESERVER_IP}" | sudo tee /etc/resolver/consul
		echo "port 8600" | sudo tee -a /etc/resolver/consul
		;;

	restart) ## %% 🔄  Restart Harpoon Core Services
		${HARPOON_DOCKER_COMPOSE} stop
		${HARPOON_DOCKER_COMPOSE} rm -f -v
		${HARPOON_DOCKER_COMPOSE} up -d
		;;

	clean) ## %% 🗑  Uninstall Harpoon
		${HARPOON_DOCKER_COMPOSE} down --rmi all -v
		docker network rm ${HARPOON_DOCKER_NETWORK} || true

		if [ ${CUSTOM_DOMAIN:-} ]; then
			sudo rm -f /etc/resolver/${CUSTOM_DOMAIN}
		fi

		sudo rm -f /etc/resolver/harpoon.dev
		sudo rm -f /etc/resolver/consul
		;;

	#traefik:storeconfig) ## %% Upload the Traefik configuration to Consul
	#	traefik_storeconfig ;;

	services:list) ## %% List services available in Harpoon
		services ;;

	services:status) ## %% Display the status for all supporting services
		services_status ;;

	couchbase*)
		handle_service couchbase ${command} ;;

	elk*)
		handle_service elk ${command} ;;

	localstack*)
		handle_service localstack ${command} ;;

	mailhog*)
		handle_service mailhog ${command} ;;

	mysql*)
		handle_service mysql ${command} ;;

	postgres*)
		handle_service postgres ${command} ;;

	redis*)
		handle_service redis ${command} ;;

	ssh-agent*)
		handle_service ssh-agent ${command} ;;

	help|*) ## Get help
		echo "Usage: harpoon command [<arg>...]"
		echo ""
		print_help ${ROOT_TASKS_FILE}
		printf "\t\033[36m%-34s\033[0m %s\n" "(service):help" "Get help for a particular service"
		echo ""
		exit 1
esac