#!/usr/bin/env bash

set -e

command=$1
args=${@:2}

export SOURCE="${BASH_SOURCE[0]}"
while [ -h "$SOURCE" ]; do # resolve $SOURCE until the file is no longer a symlink
  LOWCAL_ROOT="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
  SOURCE="$(readlink "$SOURCE")"
  [[ ${SOURCE} != /* ]] && SOURCE="$LOWCAL_ROOT/$SOURCE" # if $SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
done

export LOWCAL_ROOT="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
export SERVICES_ROOT=${LOWCAL_ROOT}/services

export ROOT_TASKS_FILE="${LOWCAL_ROOT}/lowcal"

export LOWCAL_DOCKER_COMPOSE_CFG="${LOWCAL_ROOT}/docker-compose.yml"
export LOWCAL_DOCKER_COMPOSE="docker-compose -f ${LOWCAL_DOCKER_COMPOSE_CFG}"

source ${LOWCAL_ROOT}/core/vars/vars.sh

print_help() {
	help=$(grep -E '^\t[a-zA-Z:|_-]+\)\s##\s.*$' ${1} | sort | awk 'BEGIN {FS = "\\).*?## |%%"}; {c=$1" "$2; printf "\033[36m%-34s\033[0m %s\n", c, $3}')
	echo -e "$help"
}

source ${LOWCAL_ROOT}/services/services.sh

export TRAEFIK_COMMAND="-h"

traefik_storeconfig() {
	if [ ! -f core/traefik/acme/acme.json ]; then
		echo "{ }" > core/traefik/acme/acme.json
	fi
	chmod 600 core/traefik/acme/acme.json
	${LOWCAL_DOCKER_COMPOSE} run --rm traefik storeconfig
}

export HTTPIE="docker run --rm -i -v ${PWD}:${PWD} -w ${PWD} --net=lowcal -e 'TERM=xterm' alpine/httpie"

case "$command" in
	docker) ## <arg>...	%% 🐳  Run docker in the Lowcal environment
		docker ${args} ;;

	docker-compose|dc) ## <arg>... %% 🐳  Run docker-compose in the Lowcal environment
		${LOWCAL_DOCKER_COMPOSE} ${args} ;;

	env) ## %% Show environment variables
		env ;;

	http) ## <arg...> %% 🌎  HTTPie
		${HTTPIE} ${args} ;;

	show-nameserver-ip)
		echo ${NAMESERVER_IP} ;;

	install) ## %% ▶️  Install Lowcal
		docker network create lowcal --subnet 10.254.253.0/24 || true
		${LOWCAL_DOCKER_COMPOSE} pull
		${LOWCAL_DOCKER_COMPOSE} up -d cadvisor dnsmasq consul
#		sleep 10
#		traefik_storeconfig
		${LOWCAL_DOCKER_COMPOSE} up -d traefik

		sudo mkdir -p /etc/resolver

		# Add fixed loopback alias for container connectivity to services running locally (when running Docker for Mac)
		uname | grep Darwin && sudo ifconfig lo0 alias 10.254.252.1/32 || true

		#sudo ifconfig lo:0 10.254.253.1/32

		if [ ${CUSTOM_DOMAIN} ]; then
			echo "nameserver ${NAMESERVER_IP}" | sudo tee -a /etc/resolver/${CUSTOM_DOMAIN}
		fi

		echo "nameserver ${NAMESERVER_IP}" | sudo tee -a /etc/resolver/lowcal.dev
		echo "nameserver ${NAMESERVER_IP}" | sudo tee -a /etc/resolver/consul
		echo "port 8600" | sudo tee -a /etc/resolver/consul
		;;

	clean) ## %% 🗑  Uninstall Lowcal
		${LOWCAL_DOCKER_COMPOSE} down --rmi all -v
		docker network rm lowcal || true

		if [ ${CUSTOM_DOMAIN} ]; then
			sudo rm -f /etc/resolver/${CUSTOM_DOMAIN}
		fi

		sudo rm -f /etc/resolver/lowcal.dev
		sudo rm -f /etc/resolver/consul
		;;

	#traefik:storeconfig) ## %% Upload the Traefik configuration to Consul
	#	traefik_storeconfig ;;

	services:list) ## %% List services available in Lowcal
		services ;;

	couchbase*)
		handle_service couchbase ${command} "-f ${LOWCAL_ROOT}/services/couchbase/couchbase.yml" ;;

	localstack*)
		handle_service localstack ${command} "-f ${LOWCAL_ROOT}/services/localstack/localstack.yml" ;;

	mysql*)
		handle_service mysql ${command} "-f ${LOWCAL_ROOT}/services/mysql/mysql.yml" ;;

	ssh-agent*)
		handle_service ssh-agent ${command} "-f ${LOWCAL_ROOT}/services/ssh-agent/ssh-agent.yml" ;;

	help|*) ## Get help
		echo "Usage: lowcal command [<arg>...]"
		echo ""
		print_help ${ROOT_TASKS_FILE}
		printf "\t\033[36m%-34s\033[0m %s\n" "(service):help" "Get help for a particular service"
		echo ""
		exit 1
esac