version: '3.4'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:${ES_VERSION}
    container_name: harpoon_elasticsearch
    environment:
      - discovery.type=single-node
      - http.cors.enabled=true
      - http.cors.allow-origin=*
      - http.cors.allow-headers=Authorization
      - cluster.name=harpoon
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - LOGSPOUT=ignore
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata:/usr/share/elasticsearch/data
    labels:
      - "traefik.backend=elasticsearch"
      - "traefik.port=9200"
      - "traefik.frontend.rule=Host:${ES_HOSTS}"
      - "traefik.frontend.entryPoints=${FRONTEND_ENTRYPOINTS}"
      - "traefik.docker.network=${HARPOON_DOCKER_NETWORK}"
      - "traefik.tags=${TRAEFIK_DOCKER_TAGS}"
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      default:
        aliases:
          - elasticsearch.${HARPOON_INT_DOMAIN}
          - es.${HARPOON_INT_DOMAIN}

  logstash:
    image: docker.elastic.co/logstash/logstash:${LOGSTASH_VERSION}
    container_name: harpoon_logstash
    environment:
      - xpack.monitoring.elasticsearch.url=${ELASTICSEARCH_URL}
      - LOGSPOUT=ignore
    volumes:
      - ./logstash/pipeline/:/usr/share/logstash/pipeline/
    labels:
      - "traefik.backend=logstash"
      - "traefik.port=9600"
      - "traefik.frontend.rule=Host:${LOGSTASH_HOSTS}"
      - "traefik.frontend.entryPoints=${FRONTEND_ENTRYPOINTS}"
      - "traefik.docker.network=${HARPOON_DOCKER_NETWORK}"
      - "traefik.tags=${TRAEFIK_DOCKER_TAGS}"
    ports:
      - 5044
      - 8911
      - 9600
    networks:
      default:
        aliases:
          - logstash.${HARPOON_INT_DOMAIN}

  kibana:
    image: docker.elastic.co/kibana/kibana:${KIBANA_VERSION}
    container_name: harpoon_kibana
    environment:
      SERVER_NAME: ${KIBANA_SERVER_NAME}
      ELASTICSEARCH_URL: ${ELASTICSEARCH_URL}
      LOGSPOUT: ignore
    labels:
      - "traefik.backend=kibana"
      - "traefik.port=5601"
      - "traefik.frontend.rule=Host:${KIBANA_HOSTS}"
      - "traefik.frontend.entryPoints=${FRONTEND_ENTRYPOINTS}"
      - "traefik.docker.network=${HARPOON_DOCKER_NETWORK}"
      - "traefik.tags=${TRAEFIK_DOCKER_TAGS}"
      - "SERVICE_5601_NAME=kibana"
    ports:
      - 5601
    networks:
      default:
        aliases:
          - kibana.${HARPOON_INT_DOMAIN}

  filebeat:
    image: docker.elastic.co/beats/filebeat:${FILEBEAT_VERSION}
    container_name: harpoon_filebeat
    restart: unless-stopped
    volumes:
      - ./usr/share/filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/containers/:/var/lib/docker/containers/
    user: root
    depends_on:
      - elasticsearch
      - kibana
    networks:
      default:
        aliases:
          - filebeat.${HARPOON_INT_DOMAIN}

networks:
  default:
    external:
      name: ${HARPOON_DOCKER_NETWORK}

volumes:
  esdata:
    external: true