version: '2'

services:
  elk:
    image: sebp/elk
    environment:
      - TERM=xterm
    labels:
      - "traefik.backend=elk"
      - "traefik.port=5601"
      - "traefik.frontend.rule=Host:elk.harpoon.dev, kibana.harpoon.dev"
      - "traefik.frontend.entryPoints=http"
      - "traefik.docker.network=harpoon"
      - "traefik.tags=harpoon"
    networks:
      default:
        aliases:
          - elk.harpoon.dev
          - kibana.harpoon.dev
    ports:
      - "5601"
      - "9200:9200"
      - "5044:5044"

networks:
  default:
    external:
      name: harpoon