#!/usr/bin/env bash

genvLoad() {
	source ${BATS_TEST_DIRNAME}/../$1
}

setGenvRoots() {
	export GENV_ROOT=${BATS_TEST_DIRNAME}/../
	export GENV_TASKS_ROOT=${GENV_ROOT}tasks
	export GENV_SERVICES_ROOT=${GENV_ROOT}services
	export GENV_VENDOR_ROOT=${GENV_ROOT}vendor
	export GENV_IMAGES_ROOT=${GENV_ROOT}images
	export GENV_LIB_ROOT=${GENV_ROOT}lib
	echo "GENV_ROOT: $GENV_ROOT"
	echo "GENV_TASKS_ROOT: $GENV_TASKS_ROOT"
	echo "GENV_SERVICES_ROOT: $GENV_SERVICES_ROOT"
	echo "GENV_VENDOR_ROOT: $GENV_VENDOR_ROOT"
	echo "GENV_IMAGES_ROOT: $GENV_IMAGES_ROOT"
	echo "GENV_LIB_ROOT: $GENV_LIB_ROOT"

}