#!/usr/bin/env bash

harpoonLoad() {
	source ${BATS_TEST_DIRNAME}/../$1
}

setHarpoonRoots() {
	export HARPOON_ROOT=${BATS_TEST_DIRNAME}/../
	export HARPOON_TASKS_ROOT=${HARPOON_ROOT}tasks
	export HARPOON_SERVICES_ROOT=${HARPOON_ROOT}services
	export HARPOON_VENDOR_ROOT=${HARPOON_ROOT}vendor
	export HARPOON_IMAGES_ROOT=${HARPOON_ROOT}images
	export HARPOON_LIB_ROOT=${HARPOON_ROOT}lib
	echo "HARPOON_ROOT: $HARPOON_ROOT"
	echo "HARPOON_TASKS_ROOT: $HARPOON_TASKS_ROOT"
	echo "HARPOON_SERVICES_ROOT: $HARPOON_SERVICES_ROOT"
	echo "HARPOON_VENDOR_ROOT: $HARPOON_VENDOR_ROOT"
	echo "HARPOON_IMAGES_ROOT: $HARPOON_IMAGES_ROOT"
	echo "HARPOON_LIB_ROOT: $HARPOON_LIB_ROOT"

}