version: '3.4'

services:
  mailhog:
    container_name: harpoon_mailhog
    image: mailhog/mailhog
    environment:
      - TERM=xterm
    labels:
      - "traefik.backend=mailhog"
      - "traefik.port=8025"
      - "traefik.frontend.rule=Host:${MH_HOSTS}"
      - "traefik.frontend.entryPoints=${FRONTEND_ENTRYPOINTS}"
      - "traefik.docker.network=${HARPOON_DOCKER_NETWORK}"
      - "traefik.tags=${TRAEFIK_DOCKER_TAGS}"
      - "SERVICE_1025_NAME=mailhog"
      - "SERVICE_8025_NAME=mailhog-ui"
    ports:
      - "1025:1025"
      - "8025"
    networks:
      default:
        aliases:
          - mailhog.${HARPOON_INT_DOMAIN}

networks:
  default:
    external:
      name: ${HARPOON_DOCKER_NETWORK}