version: '2'

services:
  mailhog:
    container_name: harpoon_mailhog
    image: mailhog/mailhog
    environment:
      - TERM=xterm
    labels:
      - "traefik.backend=mailhog"
      - "traefik.port=8025"
      - "traefik.frontend.rule=Host:${MH_HOSTS}"
      - "traefik.frontend.entryPoints=${FRONTEND_ENTRYPOINTS}"
      - "traefik.docker.network=${HARPOON_DOCKER_NETWORK}"
      - "traefik.tags=${TRAEFIK_DOCKER_TAGS}"
    networks:
      default:
        aliases:
          - mailhog.harpoon
          - mailhog.int.harpoon
          - mailhog.harpoon.dev
    ports:
      - "1025:1025"
      - "8025"

networks:
  default:
    external:
      name: ${HARPOON_DOCKER_NETWORK}