version: '3.4'

services:
  mysql:
    container_name: ${REPO_NAME}_mysql
    image: mysql:${MYSQL_VERSION}
    environment:
      - TERM=xterm
      - MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE
      - SERVICE_3306_NAME=mysql
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - mysql:/var/lib/mysql
    networks:
      default:
        aliases:
          - mysql.${GENV_INT_DOMAIN}

networks:
  default:
    external:
      name: ${GENV_DOCKER_NETWORK}

volumes:
  mysql:
    external: true