version: '2'

services:
  mysql:
    container_name: harpoon_mysql
    image: mysql:${MYSQL_VERSION}
    environment:
      - TERM=xterm
      - MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - mysql:/var/lib/mysql
    networks:
      default:
        aliases:
          - mysql.harpoon

networks:
  default:
    external:
      name: ${HARPOON_DOCKER_NETWORK}

volumes:
  mysql:
    external: true