filebeat.prospectors:
- type: log
  enabled: true
  paths:
    - '/var/lib/docker/containers/*/*.log'
  json.message_key: log
  json.keys_under_root: true
  processors:
  - add_docker_metadata: ~
output.elasticsearch:
  hosts: ["genv_elasticsearch:9200"]
#output.logstash:
#  hosts: ["genv_logstash:5044"]
setup.kibana:
  host: "genv_kibana:5601"