version: '2'

services:
  couchbase:
    image: couchbase:${COUCHBASE_VERSION}
    environment:
      - TERM=xterm
    labels:
      - "traefik.backend=couchbase"
      - "traefik.port=8091"
      - "traefik.frontend.rule=Host:${CB_HOSTS}"
      - "traefik.frontend.entryPoints=${FRONTEND_ENTRYPOINTS}"
      - "traefik.docker.network=${HARPOON_DOCKER_NETWORK}"
      - "traefik.tags=${TRAEFIK_DOCKER_TAGS}"
    networks:
      default:
        aliases:
          - couchbase.harpoon.dev
    ports:
      - "8091-8094:8091-8094"
      - "11210:11210"

  couchbase-provisioner:
    image: wheniwork/couchbase-provisioner:master
    environment:
      - TERM=xterm
    labels:
      - "traefik.backend=couchbase-provisioner"
      - "traefik.port=8080"
      - "traefik.frontend.rule=Host:${CBPVR_HOSTS}"
      - "traefik.frontend.entryPoints=${FRONTEND_ENTRYPOINTS}"
      - "traefik.docker.network=${HARPOON_DOCKER_NETWORK}"
      - "traefik.tags=${TRAEFIK_DOCKER_TAGS}"
    networks:
      default:
        aliases:
          - couchbase-provisioner.harpoon.dev
          - cbpvr.harpoon.dev
    ports:
      - "8080"
    volumes:
      - ./config.yaml:/etc/couchbase-provisioner/config.yaml

networks:
  default:
    external:
      name: ${HARPOON_DOCKER_NETWORK}