version: '2'

services:
  couchbase:
    container_name: harpoon_couchbase
    hostname: ${CB_HOST}
    image: couchbase:${COUCHBASE_VERSION}
    environment:
      - TERM=xterm
    labels:
      - "traefik.backend=couchbase"
      - "traefik.port=8091"
      - "traefik.frontend.rule=Host:${CB_HOST}"
      - "traefik.frontend.entryPoints=${FRONTEND_ENTRYPOINTS}"
      - "traefik.docker.network=${HARPOON_DOCKER_NETWORK}"
      - "traefik.tags=${TRAEFIK_DOCKER_TAGS}"
    ports:
      - "8091-8094:8091-8094"
      - "11207:11207"
      - "11210-11211:11210-11211"
      - "18091-18093:18091-18093"
    networks:
      default:
        aliases:
          - ${CB_HOST}
          - couchbase.int.harpoon
    volumes:
      - couchbase:/opt/couchbase/var

  couchbase-provisioner:
    container_name: harpoon_couchbase-provisioner
    image: wheniwork/couchbase-provisioner:master
    environment:
      - TERM=xterm
    labels:
      - "traefik.backend=couchbase-provisioner"
      - "traefik.port=8080"
      - "traefik.frontend.rule=Host:${CBPVR_HOSTS}"
      - "traefik.frontend.entryPoints=${FRONTEND_ENTRYPOINTS}"
      - "traefik.docker.network=${HARPOON_DOCKER_NETWORK}"
      - "traefik.tags=${TRAEFIK_DOCKER_TAGS}"
    networks:
      default:
        aliases:
          - couchbase-provisioner.harpoon
          - cbpvr.harpoon
          - couchbase-provisioner.int.harpoon
          - cbpvr.int.harpoon
          # deprecated
          - couchbase-provisioner.harpoon.dev
          - cbpvr.harpoon.dev
    ports:
      - "8080"
    volumes:
      - ./provisioner_config.yaml:/etc/couchbase-provisioner/config.yaml

networks:
  default:
    external:
      name: ${HARPOON_DOCKER_NETWORK}

volumes:
  couchbase:
    external: true