version: '3.4'

services:
  couchbase:
    container_name: harpoon_couchbase
    hostname: couchbase.${HARPOON_INT_DOMAIN}
    image: couchbase:${COUCHBASE_VERSION}
    environment:
      - TERM=xterm
    labels:
      - "traefik.backend=couchbase"
      - "traefik.port=8091"
      - "traefik.frontend.rule=Host:${CB_HOSTS}"
      - "traefik.frontend.entryPoints=${FRONTEND_ENTRYPOINTS}"
      - "traefik.docker.network=${HARPOON_DOCKER_NETWORK}"
      - "traefik.tags=${TRAEFIK_DOCKER_TAGS}"
      - "SERVICE_8091_NAME=couchbase"
    ports:
      - "8091-8094:8091-8094"
      - "11207:11207"
      - "11210-11211:11210-11211"
      - "18091-18093:18091-18093"
    networks:
      default:
        aliases:
          - couchbase.${HARPOON_INT_DOMAIN}
    volumes:
      - couchbase:/opt/couchbase/var

  couchbase-provisioner:
    container_name: harpoon_couchbase-provisioner
    image: koinotice/couchbase-provisioner:master
    environment:
      - TERM=xterm
    labels:
      - "traefik.backend=couchbase-provisioner"
      - "traefik.port=8080"
      - "traefik.frontend.rule=Host:${CBPVR_HOSTS}"
      - "traefik.frontend.entryPoints=${FRONTEND_ENTRYPOINTS}"
      - "traefik.docker.network=${HARPOON_DOCKER_NETWORK}"
      - "traefik.tags=${TRAEFIK_DOCKER_TAGS}"
      - "SERVICE_8080_NAME=cbpvr"
    ports:
      - "8080"
    networks:
      default:
        aliases:
          - couchbase-provisioner.${HARPOON_INT_DOMAIN}
          - cbpvr.${HARPOON_INT_DOMAIN}
    volumes:
      - ./provisioner_config.yaml:/etc/couchbase-provisioner/config.yaml

networks:
  default:
    external:
      name: ${HARPOON_DOCKER_NETWORK}

volumes:
  couchbase:
    external: true