version: '3.4'

services:
  redis-commander:
    container_name: ${REPO_NAME}_redis-commander
    image: rediscommander/redis-commander:${REDIS_COMMANDER_VERSION}
    restart: always
    environment:
      - REDIS_HOSTS
      - REDIS_PORT
    labels:
      - "traefik.backend=redis-commander"
      - "traefik.port=8081"
      - "traefik.frontend.rule=Host:${REDIS_COMMANDER_HOSTS}"
      - "traefik.frontend.entryPoints=${FRONTEND_ENTRYPOINTS}"
      - "traefik.docker.network=${GENV_DOCKER_NETWORK}"
      - "traefik.tags=${TRAEFIK_DOCKER_TAGS}"
      - "SERVICE_8081_NAME=redis-commander"
    networks:
      default:
        aliases:
          - redis-commander.${GENV_INT_DOMAIN}
    ports:
      - "8081"

networks:
  default:
    external:
      name: ${GENV_DOCKER_NETWORK}
