version: '2'

services:
  postgres:
    container_name: harpoon_postgres
    image: postgres:${POSTGRES_VERSION}
    environment:
      - TERM=xterm
      - POSTGRES_PASSWORD
      - POSTGRES_USER
      - POSTGRES_DB
      - POSTGRES_INITDB_ARGS
      - POSTGRES_INITDB_XLOGDIR
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      default:
        aliases:
          - postgres.int.harpoon
networks:
  default:
    external:
      name: ${HARPOON_DOCKER_NETWORK}

volumes:
  pgdata:
    external: true