version: '3.4'

services:
  postgres:
    container_name: harpoon_postgres
    image: postgres:${POSTGRES_VERSION}
    environment:
      - TERM=xterm
      - POSTGRES_PASSWORD
      - POSTGRES_USER
      - POSTGRES_DB
      - POSTGRES_INITDB_ARGS
      - POSTGRES_INITDB_XLOGDIR
      - SERVICE_5432_NAME=postgres
    ports:
      - "${POSTGRES_PORT}:5432"
    networks:
      default:
        aliases:
          - postgres.${HARPOON_INT_DOMAIN}
    volumes:
      - pgdata:/var/lib/postgresql/data

networks:
  default:
    external:
      name: ${HARPOON_DOCKER_NETWORK}

volumes:
  pgdata:
    external: true