version: '3.4'

services:
  portainer:
    container_name: harpoon_portainer
    command: --no-auth
    image: portainer/portainer
    environment:
      - TERM=xterm
    labels:
      - "traefik.backend=portainer"
      - "traefik.port=9000"
      - "traefik.frontend.rule=Host:${PORTAINER_HOSTS}"
      - "traefik.frontend.entryPoints=${FRONTEND_ENTRYPOINTS}"
      - "traefik.docker.network=${HARPOON_DOCKER_NETWORK}"
      - "traefik.tags=${TRAEFIK_DOCKER_TAGS}"
      - "SERVICE_9000_NAME=portainer"
    ports:
      - "9000"
    networks:
      default:
        aliases:
          - portainer.${HARPOON_INT_DOMAIN}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  default:
    external:
      name: ${HARPOON_DOCKER_NETWORK}