version: '3.4'

services:
  ss2:
    container_name: ${REPO_NAME}_ss2
    image: koinotice/ss2:${SS2_VERSION}
    environment:
      - TERM=xterm
    labels:
      - "SERVICE_12222_NAME=ss2"
    ports:
      - "${SS2_PORT}:12222"
    command:
      -s "ss://aes-256-cfb:${SS2_PASSWORD}@0.0.0.0:12222" -verbose

    networks:
      default:
        aliases:
          - ss2.${GENV_INT_DOMAIN}

networks:
  default:
    external:
      name: ${GENV_DOCKER_NETWORK}