version: '3.4'

services:
  redis:
    container_name: genv_redis
    image: redis:${REDIS_VERSION}
    environment:
      - TERM=xterm
    labels:
      - "SERVICE_6379_NAME=redis"
    ports:
      - "${REDIS_PORT}:6379"
    networks:
      default:
        aliases:
          - redis.${GENV_INT_DOMAIN}

networks:
  default:
    external:
      name: ${GENV_DOCKER_NETWORK}