version: '2'

services:
  localstack:
    container_name: harpoon_localstack
    image: atlassianlabs/localstack
    environment:
      - TERM=xterm
      - SERVICES=${LOCALSTACK_SERVICES}
      - DEFAULT_REGION
      - HOSTNAME=${HARPOON_DOCKER_HOST_IP}
      - KINESIS_ERROR_PROBABILITY
      - DYNAMODB_ERROR_PROBABILITY
      - LAMBDA_EXECUTOR
      - DATA_DIR
      - DOCKER_HOST="unix:///var/run/docker.sock"
    labels:
      - "traefik.backend=localstack"
      - "traefik.port=8080"
      - "traefik.frontend.rule=Host:${LS_HOSTS}"
      - "traefik.frontend.entryPoints=${FRONTEND_ENTRYPOINTS}"
      - "traefik.docker.network=${HARPOON_DOCKER_NETWORK}"
      - "traefik.tags=${TRAEFIK_DOCKER_TAGS}"
    networks:
      default:
        aliases:
          - localstack.harpoon
    ports:
      - "8080"
      - ${PORT_MAPPINGS}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${TMP_DIR}:${TMP_DIR}

  aws:
    image: cgswong/aws:aws
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_REGION
    volumes:
      - ~/.aws:/root/.aws

networks:
  default:
    external:
      name: ${HARPOON_DOCKER_NETWORK}