version: '3.4'

services:
  ld-relay:
    container_name: harpoon_ld_relay
    image: wheniwork/ld-relay
    environment:
      - TERM=xterm
      - LD_ENV_dev
      - LD_PREFIX_dev
      - USE_REDIS
      - REDIS_HOST
      - REDIS_PORT
      - REDIS_TTL
      - USE_EVENTS
      - EVENTS_HOST
      - EVENTS_SEND
      - EVENTS_FLUSH_INTERVAL
      - EVENTS_SAMPLING_INTERVAL
    labels:
      - "traefik.backend=ld-relay"
      - "traefik.port=8030"
      - "traefik.frontend.rule=Host:${LDRELAY_HOSTS}"
      - "traefik.frontend.entryPoints=${FRONTEND_ENTRYPOINTS}"
      - "traefik.docker.network=${HARPOON_DOCKER_NETWORK}"
      - "traefik.tags=${TRAEFIK_DOCKER_TAGS}"
    ports:
      - "${LD_RELAY_PORT}:8030"
    networks:
      default:
        aliases:
          - ld-relay.${HARPOON_INT_DOMAIN}
          - ldrelay.${HARPOON_INT_DOMAIN}

networks:
  default:
    external:
      name: ${HARPOON_DOCKER_NETWORK}