version: '3.4'

services:
  sqs-admin:
    container_name: genv_sqs-admin
    image: koinotice/sqs-admin
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_REGION
      - SQS_ENDPOINT=${SQS_ENDPOINT}
      - SQS_ADMIN_PORT=${SQS_ADMIN_PORT}
    labels:
      - "traefik.backend=sqs-admin"
      - "traefik.port=${SQS_ADMIN_PORT}"
      - "traefik.frontend.rule=Host:${SQS_ADMIN_HOSTS}"
      - "traefik.frontend.entryPoints=${FRONTEND_ENTRYPOINTS}"
      - "traefik.docker.network=${GENV_DOCKER_NETWORK}"
      - "traefik.tags=${TRAEFIK_DOCKER_TAGS}"
    ports:
      - "${SQS_ADMIN_PORT}"
    networks:
      default:
        aliases:
          - sqs-admin.${GENV_INT_DOMAIN}
          - sqsadmin.${GENV_INT_DOMAIN}

networks:
  default:
    external:
      name: ${GENV_DOCKER_NETWORK}