version: '3.4'

services:
  blackfire:
    container_name: genv_blackfire
    image: blackfire/blackfire
    environment:
      - BLACKFIRE_LOG_LEVEL
      - BLACKFIRE_SERVER_ID
      - BLACKFIRE_SERVER_TOKEN
    networks:
      default:
        aliases:
          - blackfire.${GENV_INT_DOMAIN}
    labels:
      - "SERVICE_8707_NAME=blackfire"
    ports:
      - "8707"
    restart: on-failure

networks:
  default:
    external:
      name: ${GENV_DOCKER_NETWORK}